config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: %i[create index update destroy]
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, :last_name, presence: true
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author
  validates :body, presence: true

  enum status: %i[unpublished published]
end

app/models/post.rb
class Post < ApplicationRecord
  include ActionView::Helpers::DateHelper
  has_many :comments, dependent: :delete_all
  validates :title, presence: true, length: { in: 5..99 }
  validates :content, presence: true
  belongs_to :author
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :post

  def index
    @comments = Comment.unpublished
    redirect_to post_path(@post)
  end

  def create
    @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.published!
    redirect_to post_path(@comment.post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :status, :post_id, :author_id)
  end

  def post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = if params[:unpublished_comments]
                  @post.comments.unpublished
                else
                  @post.comments.published
                end
    @post.post_views_count += 1
    @post.save
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :image, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p><%== comment.body %></p>
<p><%= comment.author.full_name %></p>
<p><%= comment.status %></p>
<p>
  <% if comment.unpublished? %>
  <div class='btn btn-danger'>
    <%= link_to 'Publish Comment', post_comment_path(comment.post, comment), method: :patch %>
  </div>
<% end %>
</p>


<p class="fw-lighter">Updated: <%= distance_of_time_in_words(comment.updated_at, Time.now) %> ago.</p>
<p><%= link_to "Delete Comment", [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></p>
<hr />

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build] do |form| %>
  <p>
  <div class="field">
    <%= form.label :body, "Comment" %>
    <br>
    <%= form.text_area :body %>
  </div>
  </p>

  <p>
  <div class='field'>
    <%= form.select(:author_id, Author.all.collect {|a| [ a.full_name, a.id ] }, {}, {:class => "select_author"}) %>
  </div>
  </p>

  <p>
  <div class="actions">
    <%= form.submit %>
  </div>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image, class: "form-label" %>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.select :author_id, Author.all.collect { |a| [a.first_name, a.id] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container-fluid">

  <div >
    <h3>POSTS</h3>
    <hr>
    <% @posts.each do |post| %>
      <div class="post_title">
        <h2><%= post.title %></h2>
        <h6><i class="bi bi-clock"></i>Post by: <%= post.author.full_name %></h6>
      </div>
      <div class="post_content">
        <%= image_tag post.image %>
        <p><%= post.content %></p>
        <p>Views: <%= post.post_views_count%> </p>
      </div>
      <%= link_to 'Show', post %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
      <hr>
    <% end %>
    <br><br>
    <%= link_to 'New Post', new_post_path %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @post.author.full_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <%= image_tag @post.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p><strong>Comments:</strong></p>
  <p class="fw-light">
    <%= render @comments %>
  </p>

  <%= render 'comments/form', locals: { post: @post } %>

</p>

<div class='btn btn-warning'>
  <%= link_to 'Unpublished comments', post_path(@post, unpublished_comments: 1), method: :get %>
</div>
<br>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', posts_path %>